spring:
  config:
    import: "optional:configserver:http://config-service:8888"
    activate:
      on-profile: docker
---
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"